DROP DATABASE IF EXISTS BaseballSchema;

CREATE DATABASE BaseballSchema;

USE BaseballSchema;

-- Savant data
CREATE TABLE Players (
	player_id	 			INT NOT NULL AUTO_INCREMENT,
	last_name				VARCHAR(20),
    first_name              VARCHAR(20),
    position                VARCHAR(20),
	bats					VARCHAR(1),
    throws                  VARCHAR(1),
    height                  INT,
    weight                  INT,
    cur_team                VARCHAR(20),
    draft_team              VARCHAR(20),
    draft_pick              INT,
    draft_year              INT,
    high_school             VARCHAR(20),
    school                  VARCHAR(20),
    debut                   DATE,
    birthdate               DATE,

	PRIMARY KEY (player_id)
);

-- bsb reference data
CREATE TABLE Game (
    game_id                 INT NOT NULL AUTO_INCREMENT,
    date_game               DATE,
	home_team_ID    	    VARCHAR(3),
	away_team_ID  			VARCHAR(3),
    home_score              INT,            
    away_score              INT,
	PRIMARY KEY (game_id)
);

CREATE TABLE PitcherSeasonStats (
    player_id               INT,
    season                  YEAR,
	G	 			        INT,
	IP	 		            FLOAT,
    PA                      INT,
	AB	 		            INT,
	H		 	            INT,
	1B					    INT,
	2B				        INT,
	3B				        INT,
    HR                      INT,
    K                       INT,
    BB                      INT,
    K_percent               FLOAT,
    BB_percent              FLOAT,
    BAA                     FLOAT, 
    SLG                     FLOAT,
    OBP                     FLOAT,
    OPS                     FLOAT,
    ER                      INT,
    R                       INT,
    SV                      INT,    
    BS                      INT,
    W                       INT,
    L                       INT,
    ERA                     FLOAT,
    xBA                     FLOAT,
    xSLG                    FLOAT,
    wOBA                    FLOAT,
    xwOBA                   FLOAT,
    xOBP                    FLOAT,
    xISO                    FLOAT,
    exit_velocity_avg       FLOAT,
    launch_angle_avg        FLOAT,
    sweet_spot_percent      FLOAT,
    barrel_batted_rate      FLOAT,
    Pitches                 INT,
    four_seam_percent       FLOAT,
    four_seam_avg_mph       FLOAT,
    four_seam_avg_spin      INT,
    slider_percent          FLOAT,
    slider_avg_speed        FLOAT,
    slider_avg_spin         INT,
    changeup_percent        FLOAT,
    changeup_avg_speed      FLOAT,
    changeup_avg_spin       INT,
    curveball_percent       FLOAT,
    curveball_avg_speed     FLOAT,
    curveball_avg_spin      INT,
    sinker_percent          FLOAT,
    sinker_avg_speed        FLOAT,
    sinker_avg_spin         INT,
    cutter_percent          FLOAT,
    cutter_avg_speed        FLOAT,
    cutter_avg_spin         INT,
    splitter_percent        FLOAT,
    splitter_avg_speed      FLOAT,
    splitter_avg_spin       INT,
    knuckle_percent         FLOAT,
    knuckle_avg_speed       FLOAT,
    knuckle_avg_spin        INT,
	PRIMARY KEY (player_id, season),
    FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id)
);

CREATE TABLE HitterSeasonStats (
    player_id               INT,
    season                  YEAR,
    G                       INT,
    AB                      INT,
    PA                      INT,
    H                       INT,
    1B	                    INT,
    2B	                    INT,
    3B	                    INT,
    HR                      INT,
    K                       INT,
    BB                      INT,
    K_percent               FLOAT,
    BB_percent              FLOAT,
    Average                 FLOAT,
    SLG                     FLOAT,
    OBP                     FLOAT,
    OPS                     FLOAT,
    RBI                     INT,
    SB                      INT,
    HBP                     INT,
    R                       INT,
    SB_percent              INT,
    xBA                     FLOAT,
    xSLG                    FLOAT,
    wOBA                    FLOAT,
    xwOBA                   FLOAT, 
    xOBP                    FLOAT,
    xISO                    FLOAT,
    exit_velocity_avg       FLOAT,
    launch_angle_avg        FLOAT,
    sweet_spot_percent      FLOAT,
    barrel_rate             FLOAT,
    groundballs_percent     FLOAT,
    flyballs_percent        FLOAT,
    linedrives_percent      FLOAT,
    popups_percent          FLOAT,
    sprint_speed            FLOAT,
	PRIMARY KEY (player_id),
    FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id)
);

CREATE TABLE HitterPlaysIn (
    player_id               INT,
    game_id                 INT,
    PA                      INT,
    AB                      INT,
    H                       INT,
    1B	                    INT,
    2B                      INT,
    3B                      INT,
    HR                      INT,
    K                       INT,
    BB                      INT,
    HBP                     INT,
    R                       INT,
    RBI                     INT,
    SB                      INT,
    AVG                     FLOAT,
    OBP                     FLOAT,
    SLG                     FLOAT,
    OPS                     FLOAT,
	PRIMARY KEY (player_id, game_id),
    FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id),
    FOREIGN KEY (game_id) REFERENCES GAME(game_id)
);

CREATE TABLE PitcherPlaysIn (
    player_id               INT,
    game_id                 INT,
    decision                VARCHAR(1),
    IP                      FLOAT,
    H                       INT,
    R                       INT,
    ER                      INT,
    BB                      INT,
    HBP                     INT,
    K                       INT,
    BF                      INT,
    AB                      INT,
    pitches                 INT,
    strikes                 INT,
    ERA                     FLOAT,
	PRIMARY KEY (player_id, game_id),
    FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id),
    FOREIGN KEY (game_id) REFERENCES GAME(game_id)
);




