DROP DATABASE IF EXISTS Baseball;

CREATE DATABASE Baseball;

USE Baseball;

-- Savant data
CREATE TABLE Players (
	player_id	 			INT NOT NULL AUTO_INCREMENT,
	last_name				VARCHAR(20),
    first_name              VARCHAR(20),
    position                VARCHAR(50),
	bats					VARCHAR(10),
    throws                  VARCHAR(10),
    height                  VARCHAR(5),
    weight                  INT,
    debut                   DATE,
    birthdate               DATE,
	PRIMARY KEY (player_id)
);

-- bsb reference data
CREATE TABLE Game (
    game_id                 INT NOT NULL AUTO_INCREMENT,
    date_game               DATE,
	home_team    	    VARCHAR(3),
	away_team  			VARCHAR(3),
    home_score              INT,            
    away_score              INT,
	PRIMARY KEY (game_id)
);

CREATE TABLE PitcherSeasonStats (
    player_id               INT,
    season                  YEAR,
	G	 			        INT,
	IP	 		            FLOAT,
    PA                      INT,
	AB	 		            INT,
	H		 	            INT,
	1B					    INT,
	2B				        INT,
	3B				        INT,
    HR                      INT,
    K                       INT,
    BB                      INT,
    K_percent               FLOAT,
    BB_percent              FLOAT,
    BAA                     FLOAT, 
    SLG                     FLOAT,
    OBP                     FLOAT,
    OPS                     FLOAT,
    ER                      INT,
    R                       INT,
    SV                      INT,    
    BS                      INT,
    W                       INT,
    L                       INT,
    ERA                     FLOAT,
    xBA                     FLOAT,
    xSLG                    FLOAT,
    wOBA                    FLOAT,
    xwOBA                   FLOAT,
    xOBP                    FLOAT,
    xISO                    FLOAT,
    exit_velocity_avg       FLOAT,
    launch_angle_avg        FLOAT,
    sweet_spot_percent      FLOAT,
    barrel_rate      FLOAT,
    Pitches                 INT,
    four_seam_percent       FLOAT,
    four_seam_avg_mph       FLOAT,
    four_seam_avg_spin      INT,
    slider_percent          FLOAT,
    slider_avg_speed        FLOAT,
    slider_avg_spin         INT,
    changeup_percent        FLOAT,
    changeup_avg_speed      FLOAT,
    changeup_avg_spin       INT,
    curveball_percent       FLOAT,
    curveball_avg_speed     FLOAT,
    curveball_avg_spin      INT,
    sinker_percent          FLOAT,
    sinker_avg_speed        FLOAT,
    sinker_avg_spin         INT,
    cutter_percent          FLOAT,
    cutter_avg_speed        FLOAT,
    cutter_avg_spin         INT,
    splitter_percent        FLOAT,
    splitter_avg_speed      FLOAT,
    splitter_avg_spin       INT,
    knuckle_percent         FLOAT,
    knuckle_avg_speed       FLOAT,
    knuckle_avg_spin        INT,
	PRIMARY KEY (player_id, season),
    FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id)
);

CREATE TABLE BatterSeasonStats (
    player_id               INT,
    season                  YEAR,
    G                       INT,
    AB                      INT,
    PA                      INT,
    H                       INT,
    1B	                    INT,
    2B	                    INT,
    3B	                    INT,
    HR                      INT,
    K                       INT,
    BB                      INT,
    K_percent               FLOAT,
    BB_percent              FLOAT,
    Average                 FLOAT,
    SLG                     FLOAT,
    OBP                     FLOAT,
    OPS                     FLOAT,
    RBI                     INT,
    SB                      INT,
    HBP                     INT,
    R                       INT,
    SB_percent              INT,
    xBA                     FLOAT,
    xSLG                    FLOAT,
    wOBA                    FLOAT,
    xwOBA                   FLOAT, 
    xOBP                    FLOAT,
    xISO                    FLOAT,
    exit_velocity_avg       FLOAT,
    launch_angle_avg        FLOAT,
    sweet_spot_percent      FLOAT,
    barrel_rate      FLOAT,
    groundballs_percent     FLOAT,
    flyballs_percent        FLOAT,
    linedrives_percent      FLOAT,
    popups_percent          FLOAT,
    sprint_speed            FLOAT,
	PRIMARY KEY (player_id, season),
    FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id)
);

CREATE TABLE BatterPlaysIn (
    player_id               INT,
    game_id                 INT,
    team                VARCHAR(3),
    PA                 INT,
    AB                 INT,
    R                 INT,
    H                 INT,
    2B                 INT,
    3B                 INT,
    HR                 INT,
    RBI                 INT,
    BB                 INT,
    IBB                 INT,
    SO                 INT,
    HBP                 INT,
    SH                 INT,
    SF                 INT,
    ROE                 INT,
    GIDP                 INT,
    SB                 INT,
    CS                 INT,
    batting_avg                 FLOAT,
    onbase_perc                 FLOAT,
    slugging_perc                 FLOAT,
    onbase_plus_slugging                 FLOAT,
    batting_order_position                 INT,
    leverage_index_avg                 FLOAT,
    wpa_bat                 FLOAT,
    cli_avg                 FLOAT,
    cwpa_bat                 FLOAT,
    re24_bat                 FLOAT,
    pos_game                 VARCHAR(20),
	PRIMARY KEY (player_id, game_id),
    FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id),
    FOREIGN KEY (game_id) REFERENCES GAME(game_id)
);

CREATE TABLE PitcherPlaysIn (
    player_id               INT,
    game_id                 INT,
    team                    VARCHAR(3),
    days_rest              INT,
    IP                      FLOAT,
    H                       INT,
    R                       INT,
    ER                      INT,
    BB                      INT,
    SO                      INT,
    HR                      INT,
    HBP                     INT,
    ERA                     FLOAT,
    BF                      INT,
    pitches                 INT,
    strikes_total           INT,
    strikes_looking         INT,
    strikes_swinging        INT,
    inplay_gb_total         INT,
    inplay_fb_total         INT,
    inplay_ld         INT,
    inplay_pu         INT,
    inplay_unk         INT,
    inherited_runners         INT,
    inherited_score         INT,
    SB         INT,
    CS         INT,
    pickoffs         INT,
    AB         INT,
    2B         INT,
    3B         INT,
    IBB         INT,
    GIDP         INT,
    SF         INT,
    ROE         INT,
    leverage_index_avg         FLOAT,
    wpa_def         FLOAT,
    cwpa_def         FLOAT,
    re24_def         FLOAT,
	PRIMARY KEY (player_id, game_id),
    FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id),
    FOREIGN KEY (game_id) REFERENCES GAME(game_id)
);





